# Generated by Django 3.0.5 on 2020-09-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temp', models.FloatField()),
                ('weather', models.CharField(max_length=20)),
                ('condition', models.IntegerField(choices=[(0, 'good'), (1, 'normal'), (2, 'bad')])),
                ('input_date', models.DateField(unique=True)),
                ('action', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')])),
            ],
        ),
    ]
